### ISSUE TITLE
Symphonia decoder crashes for broken files

### ISSUE THREAD

**Issue by jhbruhn** [10buttons/awedio#1]
I am using the symphonia decoder with files that sometimes might be broken. If that is the case, the application panics due to this line:

https://github.com/10buttons/awedio/blob/58259816b4bad6503fdabfde9c475d878a466af8/src/sounds/decoders/symphonia.rs#L129

Before I open a PR to fix this problem: Was there a specific reason you didn't insert a `?` there? It seems at least that part of the code supported Result from the start. According to the symphonia docs, one should actually continue decoding the next packets if it is a DecodeError or IoError, which is what I want to implement.

BTW: Thanks for the nice crate! I used it to implement a hyper/tokio based backend which streams an audio stream as mp3 via HTTP. :)

**Comment by benhansen-io** [comment]
Thanks for bringing up this issue and I am very glad you have found the crate to be useful. Yeah the error handling of this particular file can definitely be improved; I don't remember why I wrote it that way or why I didn't fix it in https://github.com/10buttons/awedio/commit/f68b09cc7fc1a4c53c896182c341e72d13748443 so go ahead and fix however you think is best. Thanks for being willing to submit a PR!

And yes if Symphonia says we are supposed to continue if there is a DecodeError I am fine to do that. Ideally if you can put a comment in the code referencing Symphonia's docs that says it that will help in the future. Also in the future if someone cares we can enable a strict mode which returns all errors so the caller can decide whether to continue polling for samples or not.
